#' @title Computer layer outputs
#' @description This function returns an array of outputs
#' from a given layer.
#' @param inputs A matrix of size (N, 1), where N is the size
#' of the layer that is going to receive such inputs. (matrix)
#' @param layer A layer object generated by create_layer (list)
#' @author Eduardo Kapp
compute_layer <- function(inputs, layer) {
  outputs <- layer$weights %*% inputs + layer$biases
  return(outputs)
}
